global:
 scrape_interval:     10s
 evaluation_interval: 10s

rule_files:
 - alert.yml
 
alerting:
 alertmanagers:
   - static_configs:
     - targets:
       - alertmanager:9093

scrape_configs:
 - job_name: 'prometheus'
   scrape_interval: 5s
   static_configs:
     - targets:
       - localhost:9090

 - job_name: 'scrape-exporter'
   scrape_interval: 5s
   metrics_path: '/metrics'
   static_configs:
     - targets:
       - node-exporter:9100